mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
]

polls/urls.py
from django.urls import path

from polls import views

app_name = 'polls'

urlpatterns = [
    # path('', views.index, name='index'),
    # path('detail/<int:id>', views.detail, name='detail'),
    path('', views.HomeListView.as_view(), name='index'),
    path('detail/<int:pk>', views.HomeDetaiView.as_view(), name='detail'),
    path('edit-page', views.ArticleCreateView.as_view(), name='edit_page'),
    path('update-page/<int:pk>', views.ArticleUpdateView.as_view(), name='update_page'),
    path('delete-page/<int:pk>', views.ArticleDeleteView.as_view(), name= 'delete_page'),
    path('login', views.MyLoginView.as_view(), name= 'login_page'),
    path('register', views.RegisterLoginView.as_view(), name= 'register_page'),
    path('logout', views.MyLogoutView.as_view(), name= 'logout_page'),
]

polls/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name="Владелец статьи", blank=True, null = True )
    title = models.CharField(max_length=15, verbose_name="Названия статьи")
    content = models.TextField(verbose_name="Описание статьи")
    is_published = models.BooleanField(default=True, verbose_name="Опубликована?")
    data_published = models.DateTimeField(auto_now_add=True, verbose_name="Дата публикации")

    def __str__(self):
        return self.title

    class Meta():
        verbose_name = "Стаья"
        verbose_name_plural = "Cтатьи"

polls/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Article
from django.contrib.auth.forms import AuthenticationForm
import re
from django.core.exceptions import ValidationError



# Создани Формы Создане отчета
class ArticleForm(forms.ModelForm):
    class Meta():
        model = Article
        fields = 'title', 'content'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {"class": "form-control" , "rows" : 10}


    def clean_title(self):
        title = self.cleaned_data['title']
        if re.match(r'\d' , title):
            raise ValidationError("Название не должно начинатся с цифры")
        return title


# Создани Формы Авторизации

class AuthUserForm(AuthenticationForm,forms.ModelForm):
    class Meta():
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {"class": "form-control"}

# Создани Формы регистрации

class RegisterUserForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {"class": "form-control"}

    # Пролучение авоматического шифорвание пароля
    def save(self, commit=True):
        user = super(RegisterUserForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from .models import Article
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import ArticleForm, AuthUserForm, RegisterUserForm
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin

# Cоздание с помощью функции

# def index(request):
#     article = Article.objects.all()
#     context = {
#         'article': article,
#         'title': "List newses",
#     }
#     return render(request, template_name='polls/index.html', context=context)

# def edit_page(request):
#     secces = False
#     if request.method == 'POST':
#         form = ArticleForm(request.POST)
#         if form.is_valid():
#             form.save()
#             secces = True
#     context = {
#         'list_articles' : Article.objects.all().order_by('-id'),
#         'form' : ArticleForm(),
#         'succes' : secces,
#     }
#     return render(request, template_name='polls/edit.html', context=context)

# def update_page(request, pk):
#     success_update = False
#     get_article = Article.objects.get(pk=pk)
#
#     if request.method == 'POST':
#         form = ArticleForm(request.POST, instance=get_article)
#         if form.is_valid():
#             form.save()
#             success_update = True
#
#     context = {
#         'ger_article' : get_article,
#         'update' : True,
#         'form': ArticleForm(instance=get_article),
#         'success_update' :success_update
#     }
#     return render(request, template_name='polls/edit.html', context=context)

#
# def delete_page(request, pk):
#     get_article = Article.objects.get(pk=pk)
#     get_article.delete()
#     return redirect(reverse('polls:edit_page'))


# def detail(request, id):
#     get_article = Article.objects.get(id=id)
#     context = {
#         'get_article' :get_article
#     }
#     return render(request, template_name='polls/detail.html', context=context)


# Cоздание с помощью класса
# -----------------------------------------------------------
class HomeListView(ListView):
    model = Article
    template_name = 'polls/index.html'
    context_object_name = 'article'

class HomeDetaiView(DetailView):
    model = Article
    template_name = 'polls/detail.html'
    context_object_name = 'get_article'


# Класс отображени усешной надписи по оперциям
class CustomSuccessMessageMixin:
    @property
    def success_msg(self):
        return False
    def form_valid(self, form):
        messages.success(self.request, self.success_msg)
        return super(CustomSuccessMessageMixin, self).form_valid(form)


class ArticleCreateView(LoginRequiredMixin,CustomSuccessMessageMixin,CreateView):
    model = Article
    template_name = 'polls/edit.html'
    form_class = ArticleForm
    success_msg = "Запись создана"
    success_url = reverse_lazy('polls:edit_page')
    def get_context_data(self, **kwargs):
        kwargs ['list_articles'] = Article.objects.all().order_by('-id')
        return super(ArticleCreateView, self).get_context_data(**kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super(LoginRequiredMixin, self).form_valid(form)

class ArticleUpdateView(LoginRequiredMixin,CustomSuccessMessageMixin,UpdateView):
    model = Article
    template_name = 'polls/edit.html'
    form_class = ArticleForm
    success_msg = "Запись обновлена"
    success_url = reverse_lazy('polls:edit_page')
    def get_context_data(self, **kwargs):
        kwargs ['update'] = True
        return super(ArticleUpdateView, self).get_context_data(**kwargs)
    def get_form_kwargs(self):
        kwargs =  super(ArticleUpdateView, self).get_form_kwargs()
        # проверка пользователя на принадлежность авторства
        if self.request.user !=  kwargs['instance'].author:
            return self.handle_no_permission()
        return kwargs

class ArticleDeleteView(LoginRequiredMixin,CustomSuccessMessageMixin,DeleteView):
    model = Article
    template_name = 'polls/edit.html'
    success_msg = "Запись удалена"
    success_url = reverse_lazy('polls:edit_page')
    def post(self, request, *args, **kwargs):
        messages.success(self.request, self.success_msg)
        return super(CustomSuccessMessageMixin, self).post(request)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.request.user !=  self.object.author:
            return self.handle_no_permission()
        success_url =  self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)
# - -------------------------------------------------------------------------------------------------
# Cоздание класса для Аторизации пользователя

class MyLoginView(LoginView):
    template_name = 'polls/login.html'
    form_class = AuthUserForm
    success_url = reverse_lazy('polls:edit_page')

    def get_success_url(self):
        return self.success_url

# Cоздание класса для Регистраци пользователя

class RegisterLoginView(CreateView):
    model = User
    template_name = 'polls/register.html'
    form_class = RegisterUserForm
    success_msg = "Пользователь создан"
    success_url = reverse_lazy('polls:edit_page')

# Cоздание функции для авторизации пользователя

    def form_valid(self, form):
        form_valid = super(RegisterLoginView, self).form_valid(form)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        aut_user =  authenticate(username = username, password = password)
        login(self.request, aut_user)
        return form_valid

# Cоздание класса для Выхода пользователя

class MyLogoutView(LogoutView):
    next_page = reverse_lazy('polls:login_page')

templates/polls/detail.html
{% include 'base.html' %}


{% block content %}
    <div class="container mt-5">
        <h1>Статья: {{ get_article.title }}</h1>
        <h1 class="mb-5">Дата публикации: {{ get_article.data_published }}</h1>
        <span>Текст: {{ get_article.content }}</span>
        <button class="btn btn-light float-right mt-5 border-danger rounded-pill"><a class="text-success" href="/">Вернутья назад</a></button>
    </div>
{% endblock %}

templates/polls/edit.html
{% include 'base.html' %}


{% block content %}
    <div class="container mt-5">
        <h1 class="mb-5 font-italic text-success">Админ панель : </h1>

        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary mb-5" data-toggle="modal" data-target="#exampleModal">
            Создать статью
        </button>

        {% if success_update %}
            <p style="color: red">Запись обнавлена</p>
        {% endif %}

        {% if succes %}
            <p style="color: red">Запись добавлена</p>
        {% endif %}

      {% if messages %}
        <div class="alert alert-success">
            {% for mes in messages %}
                    {{ mes }}
            {%  endfor %}
        </div>
      {% endif %}


        {% if update %}
            <p class="mt-4">Страница редактирования</p>
            <form id="update_data" method="post">
                {% csrf_token %}
                {{ form }}
            </form>
            <button form="update_data" type="submit" class="btn btn-primary mt-4">Обновить</button>

        {% else %}

            <table class="table table-bordered-5">
                <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Дата создания</th>
                    <th scope="col">Название</th>
                    <th scope="col">Редактирование</th>
                    <th scope="col">Удаление</th>
                </tr>
                </thead>
                <tbody>

                {% for item in list_articles %}
                    <tr>
                        <th scope="row">{{ item.id }}</th>
                        <td>{{ item.data_published|date:'d.m.Y' }} - {{ item.author }}</td>
                        <td>{{ item.title }}</td>
                        <td>
                            {% if request.user == item.author %}
                            <a href="{% url 'polls:update_page' item.id %}">редактировать</a>
                            {% else %}
                                Нет доступа
                            {%  endif %}
                        </td>
                        <td>
                            {% if request.user == item.author %}
                           <form id="form_delete{{ item.id }}" action="{% url 'polls:delete_page' item.id %}"
                                  method="post">{% csrf_token %}</form>
                            <a href="javascript:void()"  onclick="delete_question{{ item.id }}()">Удалить</a>
                            <script>
                                function delete_question{{ item.id }}() {
                                    if (confirm("Вы уверены?")) {
                                        document.getElementById("form_delete{{ item.id }}").submit()
                                    }
                                }
                            </script>
                            {% else %}
                                Нет доступа
                            {%  endif %}
                        </td>
                    </tr>
                    </tbody>
                {% endfor %}
            </table>
        {% endif %}

        <!-- Modal -->

        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Создание статьи</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form id="add_form" method="post">
                            {% csrf_token %}
                            {{ form }}
                        </form>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                        <button form="add_form" type="submit" class="btn btn-primary">Добавить</button>
                    </div>
                </div>
            </div>
        </div>

        <button class="btn btn-light float-right mt-5 border-danger rounded-pill"><a class="text-success"
                                                                                     href="{% url 'polls:edit_page' %}">Вернутьcя
            назад</a></button>
    </div>
{% endblock %}

templates/polls/index.html
{% include 'base.html' %}


<div class="container">


{% block content %}
    {% for item in article %}
        <ul class="list-group mt-5">
            <li class="list-group-item">
                <span class="mr-3">{{ item.title }}</span>
                <span>{{ item.content|truncatechars:"5" }}</span>
                <b>{{ item.data_published }}</b>
                <span class="float-right mr-3"><a href="{% url 'polls:detail' item.id %}">Перейти к статье</a></span>
            </li>
        </ul>
    {% endfor %}
{% endblock %}
</div>

templates/polls/login.html
{% include 'base.html' %}


{% block content %}
    <div class="container">
        <h1 class="mt-4 text-center">Авторизация</h1>
        <p><a href="/">Вернуться назад</a></p>

        <div class="col-4">
            <form id="add_form" method="post">
                {% csrf_token %}
                {{ form }}
            </form>
            <button form="add_form" type="submit" class="btn btn-primary mt-4">Добавить</button>
        </div>
    </div>
{% endblock %}

templates/polls/register.html
{% include 'base.html' %}


{% block content %}
    <h1 class="mt-4 text-center">Регистрация</h1>
    <div class="container">
    <p><a href="/">Вернуться назад</a></p>

    <div class="col-4">
        <form id="add_form" method="post">
            {% csrf_token %}
            {{ form }}
        </form>
        <button form="add_form" type="submit" class="btn btn-primary mt-4">Добавить</button>
    </div>
    </div>
{% endblock %}