mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
]

polls/urls.py
from django.urls import path

from polls import views

app_name = 'polls'

urlpatterns = [
    # path('', views.index, name='index'),
    # path('detail/<int:id>', views.detail, name='detail'),
    path('', views.HomeListView.as_view(), name='index'),
    path('detail/<int:pk>', views.HomeDetaiView.as_view(), name='detail'),
    path('edit-page', views.ArticleCreateView.as_view(), name='edit_page'),
    path('update-page/<int:pk>', views.ArticleUpdateView.as_view(), name='update_page'),
    path('delete-page/<int:pk>', views.ArticleDeleteView.as_view(), name= 'delete_page'),
    path('login', views.MyLoginView.as_view(), name= 'login_page'),
    path('register', views.RegisterLoginView.as_view(), name= 'register_page'),
    path('logout', views.MyLogoutView.as_view(), name= 'logout_page'),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <title>{% block title %} Новости{% endblock %}

    </title>
</head>
<body>

<div class="container">
    {% block header %}
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a class="nav-link
            {% url 'polls:index' as url_index %}
            {% if url_index == request.path %} active
            {% endif %}" href="{{ url_index }}">Главная</a>
            </li>
            <li class="nav-item">
                <a class="nav-link
            {% url 'polls:edit_page' as url_edit %}
            {% if url_edit == request.path %} active
            {% endif %}" href="{{ url_edit }}">Редактировать</a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link btn-danger ml-5 {% url 'polls:logout_page' as logout_edit %}"
                   href="{{ logout_edit }}">Выйти</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link {% url 'polls:login_page' as login_edit %}
                {% if login_edit == request.path %} active
                {% endif %}" href="{{ login_edit }}">Авторизация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% url 'polls:register_page' as regis_edit %}
                {% if regis_edit == request.path %} active
                {% endif %}" href="{{ regis_edit }}">Регистрация</a>
                </li>
            {% endif %}
        </ul>
        <span class="float-right text-success"> Добропожаловать: {{ request.user }}</span>
    {% endblock %}
    {% block content %}
    {% endblock %}

</div>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
</body>
</html>